out <-
    add_presentation(country = "Canada",
                     city = "Toronto",
                     lon = 10.1, lat = 24.2,
                     event = "Seminar series",
                     title = "Towards the finite-sample variance bounds for unbiased estimators",
                     presenter_name = "Ioannis", presenter_surname = "Kosmidis",
                     presenter_affiliation = "University of Warwick",
                     link = NA,
                     type = "seminar",
                     institution = "University of Toronto", department = "Department of Statistical Sciences",
                     venue = NA,
                     room = "1084",
                     year = 2019, month = 6, day = 5,
                     start_hour = 15, start_min = 30,
                     end_hour = 16, end_min = 30) %>%
    add_presentation(country = "Cyprus",
                     city = "Limassol",
                     lon = 33.115776, lat = 34.705418,
                     event = "CRoNoS & MDA 2019",
                     title = "Infinite mixtures of beta regression models for bounded-domain variables",
                     presenter_name = "Ioannis", presenter_surname = "Kosmidis",
                     presenter_affiliation = "University of Warwick",
                     link = "http://cmstatistics.org/RegistrationsV2/CRONOSMDA2019/viewSubmission.php?in=270&token=6991s35s0003891p79p68r77006qn476",
                     type = "presentation",
                     institution = NA, department = NA,
                     venue = "Poseidonia Beach Hotel",
                     room = "Triton 1+2",
                     year = 2019, month = 4, day = 14,
                     start_hour = 10, start_min = 50,
                     end_hour = 12, end_min = 50) %>%
    add_presentation(country = "United Kingdom",
                     city = "London",
                     lon = -0.110506,
                     lat = 51.513917,
                     event = "Pint of Science 2019",
                     title = "On your mark, get set, go! Data scientists making platforms for your exercise data",
                     presenter_name = "Ioannis",
                     presenter_surname = "Kosmidis",
                     presenter_affiliation = "University of Warwick",
                     link = "https://pintofscience.co.uk/event/taking-care-of-your-data",
                     type = "presentation",
                     institution = NA, department = NA,
                     venue = "Ye Olde Cock Tavern",
                     room = NA,
                     year = 2019, month = 5, day = 22,
                     start_hour = 19, start_min = 30,
                     end_hour = 21, end_min = 30) %>%
    add_presentation(country = "United Kingdom",
                     city = "Coventry",
                     lon = -0.100506,
                     lat = 52.513917,
                     event = "Young Researchers' Meeting",
                     title = "A workflow that most probably isn't yours",
                     presenter_name = "Ioannis",
                     presenter_surname = "Kosmidis",
                     presenter_affiliation = "University of Warwick",
                     link = NA,
                     type = "presentation",
                     institution = "University of Warwick", department = "Department of Statistics",
                     venue = "Mathamtical Sciences Building",
                     room = "M1.02",
                     year = 2019, month = 5, day = 28,
                     start_hour = 16, start_min = 00,
                     end_hour = 17, end_min = 00) %>%
    add_presentation(country = "United Kingdom",
                     city = "London",
                     lon = -0.110506,
                     lat = 51.513917,
                     event = "Theory and Algorithms in Data Science seminars",
                     title = "Reduced-bias inference in regression",
                     presenter_name = "Ioannis",
                     presenter_surname = "Kosmidis",
                     presenter_affiliation = "University of Warwick",
                     link = "https://turing-seminar.github.io",
                     type = "presentation",
                     institution = "The Alan Turing Institute", department = NA,
                     venue = "The Alan Turing Institute",
                     room = "Augusta",
                     year = 2019, month = 5, day = 16,
                     start_hour = 14, start_min = 00,
                     end_hour = 15, end_min = 00)



