me_warwick <- presenter(name = "Ioannis", surname = "Kosmidis", affiliation = "University of Warwick", link = "http://www.ikosmidis.com")
me_ucl <- presenter(name = "Ioannis", surname = "Kosmidis", affiliation = "University College London", link = "http://www.ikosmidis.com")


out <- add_presentation(country = "Canada",
                        city = "Toronto",
                        lon = -79.398741, lat = 43.662692,
                        event = "Seminar series",
                        title = "Towards the finite-sample variance bounds for unbiased estimators",
                        presenter = me_warwick,
                        link = NA,
                        type = "seminar",
                        institution = "University of Toronto", department = "Department of Statistical Sciences",
                        venue = NA,
                        room = "1084",
                        year = 2019, month = 6, day = 5,
                        start_hour = 15, start_min = 30,
                        end_hour = 16, end_min = 30) %>%
    add_presentation(country = "United Kingdom",
                     city = "Coventry",
                     lon = -1.560843, lat = 52.384019,
                     event = "Young Researchers' Meeting",
                     title = "A workflow that most probably isn't yours",
                     presenter = me_warwick,
                     link = "https://warwick.ac.uk/fac/sci/statistics/news/yrm/",
                     type = "presentation",
                     institution = "University of Warwick", department = "Department of Statistics",
                     venue = "Mathemtical Sciences Building",
                     room = "M1.02",
                     year = 2019, month = 5, day = 28,
                     start_hour = 16, start_min = 00,
                     end_hour = 17, end_min = 00) %>%
    add_presentation(country = "United Kingdom",
                     city = "London",
                     lon = -0.110506,
                     lat = 51.513917,
                     event = "Pint of Science 2019",
                     title = "On your mark, get set, go! Data scientists making platforms for your exercise data",
                     presenter = me_warwick,
                     link = "https://pintofscience.co.uk/event/taking-care-of-your-data",
                     type = "presentation",
                     institution = NA, department = NA,
                     venue = "Ye Olde Cock Tavern",
                     room = NA,
                     year = 2019, month = 5, day = 22,
                     start_hour = 19, start_min = 30,
                     end_hour = 21, end_min = 30) %>%
    add_presentation(country = "United Kingdom",
                     city = "London",
                     lon = -0.127630,
                     lat = 51.530206,
                     event = "Theory and Algorithms in Data Science seminars",
                     title = "Reduced-bias inference in regression",
                     presenter = me_warwick,
                     link = "https://turing-seminar.github.io",
                     type = "presentation",
                     institution = "The Alan Turing Institute", department = NA,
                     venue = "The Alan Turing Institute",
                     room = "Augusta",
                     year = 2019, month = 5, day = 16,
                     start_hour = 14, start_min = 00,
                     end_hour = 15, end_min = 00) %>%
    add_presentation(country = "Cyprus",
                     city = "Limassol",
                     lon = 33.115776, lat = 34.705418,
                     event = "CRoNoS & MDA 2019",
                     title = "Infinite mixtures of beta regression models for bounded-domain variables",
                     presenter = me_warwick,
                     link = "http://cmstatistics.org/RegistrationsV2/CRONOSMDA2019/viewSubmission.php?in=270&token=6991s35s0003891p79p68r77006qn476",
                     type = "presentation",
                     institution = NA, department = NA,
                     venue = "Poseidonia Beach Hotel",
                     room = "Triton 1+2",
                     year = 2019, month = 4, day = 14,
                     start_hour = 10, start_min = 50,
                     end_hour = 12, end_min = 50) %>%
    add_presentation(country = "United Kingdom",
                     city = "Machester",
                     lon = -2.231464, lat = 53.468149,
                     event = "Seminar series",
                     title = "Location-adjusted Wald statistics",
                     presenter = me_warwick,
                     link = NA,
                     type = "seminar",
                     institution = "University of Machester",
                     department = NA,
                     school = "School of Mathematics",
                     venue = "Alan Turing Building",
                     room = NA,
                     year = 2019, month = 4, day = 3,
                     start_hour = 14, start_min = 00,
                     end_hour = 15, end_min = 00) %>%
    add_presentation(country = "United Kingdom",
                     city = "Coventry",
                     lon = -1.560843, lat = 52.384019,
                     event = "Algorithms & Computationally Intensive Inference seminars",
                     title = "Towards the finite-sample variance bounds for unbiased estimators",
                     presenter = me_warwick,
                     link = "https://warwick.ac.uk/fac/sci/statistics/news/algorithms-seminars",
                     type = "seminar",
                     institution = "University of Warwick",
                     department = "Department of Statistics",
                     school = NA,
                     venue = "Mathemtical Sciences Building",
                     room = "MB2.23",
                     year = 2019, month = 2, day = 8,
                     start_hour = 12, start_min = 45,
                     end_hour = 14, end_min = 00) %>%
    add_presentation(country = "United Kingdom",
                     city = "Edinburgh",
                     lon = -3.175305, lat = 55.922925,
                     event = "Statistics seminar series",
                     title = "Location-adjusted Wald statistics",
                     presenter = me_warwick,
                     link = "https://www.maths.ed.ac.uk/school-of-mathematics/events",
                     type = "seminar",
                     institution = "University of Edinburgh",
                     department = NA,
                     school = "School of Mathematics",
                     venue = "James Clerk Maxwell Building",
                     room = "5323",
                     year = 2018, month = 11, day = 23,
                     start_hour = 15, start_min = 00,
                     end_hour = 16, end_min = 00) %>%
    add_presentation(country = "United Kingdom",
                     city = "Oxford",
                     lon = -1.260640, lat = 51.752846,
                     event = "Oxford R user group",
                     title = "Package and collaboration networks in CRAN",
                     presenter = me_warwick,
                     link = "https://r-oxford.github.io/index.html",
                     type = "presentation",
                     institution = NA,
                     department = NA,
                     school = NA,
                     venue = "St Peter's College",
                     room = "Dorman Centre",
                     year = 2018, month = 11, day = 05,
                     start_hour = 18, start_min = 00,
                     end_hour = 19, end_min = 30) %>%
    add_presentation(country = "Italy",
                     city = "Milan",
                     lon = 9.213268, lat = 45.517392,
                     event = "Seminar series",
                     title = "Reduced-bias inference for regression models with tractable and intractable likelihoods",
                     presenter = me_warwick,
                     link = "https://dems.unimib.it/it/eventi/reduced-bias-inference-regression-models-tractable-and-intractable-likelihoods-ioannis-kosmidis",
                     type = "seminar",
                     institution = "University of Milano-Bicocca",
                     department = "Department of Economics",
                     school = "Quantitative Methods and Business Strategy",
                     venue = "Building U7",
                     room = "2104",
                     year = 2018, month = 10, day = 24,
                     start_hour = 12, start_min = 00,
                     end_hour = 13, end_min = 00) %>%
    add_presentation(country = "Germany",
                     city = "Aachen",
                     lon = 6.068848, lat = 50.777053,
                     event = "Workshop on Challenges for Categorical Data Analysis",
                     title = "Reduced-bias estimation of models with ordinal responses",
                     presenter = me_warwick,
                     link = "https://sites.google.com/view/CCDA2018",
                     type = "presentation",
                     institution = "RWTH Aachen University",
                     department = NA,
                     school = NA,
                     venue = "Guesthouse (Haus Königshügel)",
                     room = NA,
                     year = 2018, month = 10, day = 22,
                     start_hour = 14, start_min = 30,
                     end_hour = 15, end_min = 00) %>%
    add_presentation(country = "United Kingdom",
                     city = "Coventry",
                     lon = -1.567000, lat = 52.382687,
                     event = "OxWasp Annual Workshop 2018",
                     title = "Location-adjusted Wald statistics",
                     presenter = me_warwick,
                     link = NA,
                     type = "presentation",
                     institution = "University of Warwick", department = "Department of Statistics",
                     venue = "Radcliffe Suite",
                     room = "Scarman Conference Centre",
                     year = 2019, month = 10, day = 05,
                     start_hour = 15, start_min = 20,
                     end_hour = 15, end_min = 50) %>%
    add_presentation(country = "Wales",
                     city = "Cardiff",
                     lon = -3.178679, lat = 51.485590,
                     event = "RSS 2018 International Conference",
                     title = "Beyond Beta regression: modelling bounded-domain variables in the presence of boundary observations",
                     presenter = me_warwick,
                     link = "https://events.rss.org.uk/rss/frontend/reg/absViewDocumentFE.csp?documentID=955&eventID=194",
                     type = "presentation",
                     institution = NA, department = NA,
                     venue = "Cardiff City Hall",
                     room = "Syndicate Room B",
                     year = 2019, month = 09, day = 04,
                     start_hour = 15, start_min = 40,
                     end_hour = 16, end_min = 40) %>%
        add_presentation(country = "Italy",
                     city = "Salerno",
                     lon = 14.775877, lat = 40.672802,
                     event = "ISNPS 2019",
                     title = "Mean and median bias-reducing estimating equations for meta analysis",
                     presenter = me_warwick,
                     link = "https://www.conftool.net/isnps2018/index.php?page=browseSessions&form_session=35#paperID406",
                     type = "presentation",
                     institution = NA, department = NA,
                     venue = "Grand Hotel Salerno",
                     room = NA,
                     year = 2018, month = 06, day = 12,
                     start_hour = NA, start_min = NA,
                     end_hour = NA, end_min = NA) %>%
    add_presentation(country = "United Kingdom",
                     city = "London",
                     lon = -0.131657, lat = 51.520254,
                     event = "Workshop on Machine Learning and Econometrics",
                     title = "Location-adjusted Wald statistics",
                     presenter = me_warwick,
                     link = NA,
                     type = "presentation",
                     institution = "CEMMAP", department = NA,
                     venue = "Institute for Fiscal Studies",
                     room = NA,
                     year = 2018, month = 06, day = 08,
                     start_hour = 10, start_min = 55,
                     end_hour = 11, end_min = 30) %>%
            add_presentation(country = "Austria",
                     city = "Vienna",
                     lon = 16.407343, lat = 48.214707,
                     event = "Seminar series",
                     title = "Location-adjusted Wald statistics",
                     presenter = me_warwick,
                     link = "https://www.wu.ac.at/en/statmath/research/resseminar/summer-term-2018/",
                     type = "seminar",
                     institution = "WU Vienna", department = "Institute for Statistics and Mathematics",
                     venue = "Building D4",
                     room = "D4.4.008",
                     year = 2018, month = 05, day = 04,
                     start_hour = 09, start_min = 00,
                     end_hour = 10, end_min = 00) %>%
            add_presentation(country = "United Kingdom",
                     city = "London",
                     lon = -0.116687, lat = 51.512218,
                     event = "Seminar series",
                     title = "Location-adjusted Wald statistics",
                     presenter = me_ucl,
                     link = NA,
                     type = "seminar",
                     institution = "Kings College London", department = "Department of Mathematics",
                     venue = "Strand Building",
                     room = "S4.36",
                     year = 2017, month = 12, day = 12,
                     start_hour = 14, start_min = 00,
                     end_hour = 15, end_min = 00) %>%
                add_presentation(country = "Greece",
                     city = "Athens",
                     lon = 23.732489, lat = 37.994334,
                     event = "2nd AUEB Sports Analytics Workshop 2017",
                     title = "Statistical modeling of availability to train in elite sports",
                     presenter = me_ucl,
                     link = "https://aueb-analytics.wixsite.com/sports/aueb-saw-2017",
                     type = "presentation",
                     institution = "Athens University of Economics and Business",
                     department = "Department of Statistics",
                     venue = "Athens Universitu of Economics and Business",
                     room = NA,
                     year = 2017, month = 11, day = 7,
                     start_hour = 19, start_min = 00,
                     end_hour = 20, end_min = 00) %>%
    add_presentation(country = "Austria",
                     city = "Vienna",
                     lon = 16.346876, lat = 48.220893,
                     event = "CEN ISBS Joint Conference on Biometrics & Biopharmaceutical Statistics",
                     title = "Reduced-bias estimation of models with ordinal responses",
                     presenter = me_ucl,
                     link = "http://www.professionalabstracts.com/cenisbs2017/iplanner/#/grid",
                     type = "presentation",
                     institution = NA,
                     department = NA,
                     venue = "Medical University of Vienna",
                     room = "I14/TCS041",
                     year = 2017, month = 08, day = 31,
                     start_hour = 09, start_min = 30,
                     end_hour = 10, end_min = 00) %>%
    add_presentation(country = "United Kingdom",
                     city = "Southampton",
                     lon = -1.398807, lat = 50.936310,
                     event = "S3RI Seminar",
                     title = "Reduced-bias inference for regression models with tractable and intractable likelihoods",
                     presenter = me_ucl,
                     link = "https://www.southampton.ac.uk/maths/news/seminars/2017/03/16-s3ri-seminar-ioannis-kosmidis.page",
                     type = "seminar",
                     institution = "University of Southampton",
                     department = NA,
                     school = "Mathematical Sciences",
                     venue = "Building 54",
                     room = "Lecture Theatre 5A",
                     year = 2017, month = 03, day = 16,
                     start_hour = 14, start_min = 00,
                     end_hour = 15, end_min = 00) %>%
    add_presentation(country = "Austria",
                     city = "Vienna",
                     lon = 16.351529, lat = 48.219741,
                     event = "Seminar series",
                     title = "Reduced-bias inference for regression models with tractable and intractable likelihoods",
                     presenter = me_ucl,
                     link = NA,
                     type = "seminar",
                     institution = "Medical University of Vienna",
                     school = "Center for Medical Statistics, Informatics, and Intelligent Systems",
                     department = NA,
                     venue = "Building BT88",
                     room = NA,
                     year = 2017, month = 02, day = 11,
                     start_hour = 11, start_min = 00,
                     end_hour = 12, end_min = 00) %>%
        add_presentation(country = "United Kingdom",
                     city = "Coventry",
                     lon = -1.559359, lat = 52.384249,
                     event = "CRiSM seminar series",
                     title = "Reduced-bias inference for regression models with tractable and intractable likelihoods",
                     presenter = me_ucl,
                     link = "https://warwick.ac.uk/fac/sci/statistics/event_diary/?calendarItem=094d4345576c303701578a6d89a903fa",
                     type = "seminar",
                     institution = "University of Warwick",
                     department = "Department of Statistics",
                     venue = "Zeeman Building",
                     room = "MA_B1.01",
                     year = 2017, month = 2, day = 17,
                     start_hour = 14, start_min = 00,
                     end_hour = 15, end_min = 00) %>%
        add_presentation(country = "United Kingdom",
                     city = "London",
                     lon = -1.559359, lat = 52.384249,
                     event = "Statistical Science Seminars",
                     title = "Beyond Beta regression: modelling bounded-domain variables in the presence of boundary observations",
                     presenter = me_ucl,
                     link = "https://warwick.ac.uk/fac/sci/statistics/event_diary/?calendarItem=094d4345576c303701578a6d89a903fa",
                     type = "seminar",
                     institution = "University College London",
                     department = "Department of Statistical Science",
                     venue = "1-19 Torrington Place",
                     room = "102",
                     year = 2017, month = 2, day = 09,
                     start_hour = 16, start_min = 00,
                     end_hour = 17, end_min = 00)  %>%
            add_presentation(country = "Austria",
                     city = "Innsbruck",
                     lon = 11.398236, lat = 47.269400,
                     event = "Seminar series",
                     title = "Reduced-Bias Inference in Parametric Models with Intractable Likelihoods",
                     presenter = me_ucl,
                     link = "https://www.uibk.ac.at/eeecon/research-seminars/empec/winter-term-16-17",
                     type = "seminar",
                     institution = "University of Innsbruck",
                     department = "Department of Statistics",
                     school = "Empirical Economics and Econometris Research Centre",
                     venue = "SOWI Building",
                     room = "SR7",
                     year = 2017, month = 1, day = 26,
                     start_hour = 10, start_min = 00,
                     end_hour = 11, end_min = 30) %>%
                add_presentation(country = "United Kingdom",
                     city = "Glasgow",
                     lon = -4.291964, lat = 55.873458,
                     event = "Seminar series",
                     title = "Reduced-bias inference in parametric models with tracktable and intractable likelihoods",
                     presenter = me_ucl,
                     link = "https://www.gla.ac.uk/schools/mathematicsstatistics/events/details/?id=9793",
                     type = "seminar",
                     institution = "University of Glasgow",
                     school = "School of Mathematics & Statistics",
                     venue = "Mathematics Building",
                     room = "Maths 203",
                     year = 2016, month = 11, day = 25,
                     start_hour = 15, start_min = 00,
                     end_hour = 16, end_min = 00) %>%
    add_presentation(country = "United Kingdom",
                     city = "York",
                     lon = -1.055274, lat = 53.946682,
                     event = "Seminar series",
                     title = "Reduced-bias inference in parametric models with tracktable and intractable likelihoods",
                     presenter = me_ucl,
                     link = "http://maths.york.ac.uk/www/node/15670",
                     type = "seminar",
                     institution = "University of York",
                     department = "Department of Mathematics",
                     venue = "Department of Mathematics",
                     room = NA,
                     year = 2016, month = 11, day = 24,
                     start_hour = 13, start_min = 00,
                     end_hour = 14, end_min = 00) %>%
        add_presentation(country = "Greece",
                     city = "Tinos",
                     lon = 25.163583, lat = 37.537992,
                     event = "Greek Stochastics &theta;'",
                     title = "Improving the accuracy of likelihood- based inference in meta-analysis and meta-regression",
                     presenter = me_ucl,
                     link = "http://www.stochastics.gr/meetings/theta/prog.pdf",
                     type = "presentation",
                     institution = NA,
                     department = NA,
                     venue = "Cultural Foundation of Tinos",
                     room = NA,
                     year = 2016, month = 07, day = 12,
                     start_hour = 14, start_min = 45,
                     end_hour = 15, end_min = 15) %>%
    add_presentation(country = "France",
                     city = "Rennes",
                     lon = -1.635660, lat = 48.120904,
                     event = "31st International Workshop on Statistical Modelling",
                     title = "Penalized likelihood in meta-regression",
                     presenter = me_ucl,
                     link = "https://www.lebesgue.fr/sites/default/files/sem2016/iwsm2016/programme.pdf",
                     type = "presentation",
                     institution = NA,
                     department = NA,
                     venue = "Building 4 of INSA",
                     room = "Amphi D",
                     year = 2016, month = 07, day = 07,
                     start_hour = 18, start_min = 00,
                     end_hour = 18, end_min = 20) %>%
    add_presentation(country = "United States",
                     city = "Stanford",
                     lon = -122.165330, lat = 37.429464,
                     event = "useR! 2016",
                     title = "brglm: Reduced-bias inference in generalized linear models",
                     presenter = me_ucl,
                     link = "http://user2016.r-project.org//files/abs-book.pdf",
                     type = "presentation",
                     institution = NA,
                     department = NA,
                     venue = "Stanford Institute for Economic Policy Research",
                     room = "Siepr 120",
                     year = 2016, month = 06, day = 29,
                     start_hour = 14, start_min = 15,
                     end_hour = 14, end_min = 35)



